In [12]:
import numpy as np
import pandas as pd
import random
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
import joblib

np.random.seed(42)
random.seed(42)

In [16]:
records = []

for bin_id in range(1, 21):
    fill = random.randint(5, 20)
    growth_rate = random.uniform(0.4, 1.8)  # each bin behaves differently
    
    for hour in range(0, 168):  # 7 days hourly data
        
        hour_of_day = hour % 24
        day = hour // 24
        weekend = 1 if day in [5, 6] else 0
        
        # Growth pattern: weekday vs weekend + daily cycle + noise
        base_growth = growth_rate + (0.7 if weekend else 0.2)
        daily_cycle = 0.4 * np.sin(2 * np.pi * hour_of_day / 24)
        noise = random.uniform(-1.2, 1.2)

        fill = fill + base_growth + daily_cycle + noise
        fill = max(0, min(100, fill))

        # Random collection event (bin emptied)
        if random.random() < 0.03:
            fill = random.uniform(0, 15)

        records.append({
            "bin_id": f"BIN_{bin_id}",
            "hour": hour,
            "fill_level": fill,
            "hour_of_day": hour_of_day,
            "day": day,
            "weekend": weekend
        })

df = pd.DataFrame(records)
df.head()

  bin_id  hour  fill_level  hour_of_day  day  weekend
0  BIN_1     0   16.749733            0    0        0
1  BIN_1     1   17.808667            1    0        0
2  BIN_1     2   20.421481            2    0        0
3  BIN_1     3   11.501546            3    0        0
4  BIN_1     4   12.165527            4    0        0

In [18]:
df["future_fill"] = df.groupby("bin_id")["fill_level"].shift(-6)
df = df.dropna()
df.head()

  bin_id  hour  fill_level  hour_of_day  day  weekend  future_fill
0  BIN_1     0   16.749733            0    0        0    16.731790
1  BIN_1     1   17.808667            1    0        0    18.713637
2  BIN_1     2   20.421481            2    0        0    21.272121
3  BIN_1     3   11.501546            3    0        0    23.688563
4  BIN_1     4   12.165527            4    0        0    25.602094

In [22]:
features = ["fill_level", "hour_of_day", "day", "weekend"]
target = "future_fill"

X = df[features]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model_rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=15,
    random_state=42
)

model_rf.fit(X_train, y_train)

preds = model_rf.predict(X_test)

print("MAE:", round(mean_absolute_error(y_test, preds), 2))
print("R2:", round(r2_score(y_test, preds), 3))
print("Features used:", model_rf.feature_names_in_)

MAE: 10.68
R2: 0.537
Features used: ['fill_level' 'hour_of_day' 'day' 'weekend']

In [23]:
def predict_future_fill(current_fill, hour, day, weekend):
    cols = model_rf.feature_names_in_

    row = {
        "fill_level": current_fill,
        "hour_of_day": hour,
        "day": day,
        "weekend": weekend
    }

    input_data = pd.DataFrame([[row[c] for c in cols]], columns=cols)
    return float(model_rf.predict(input_data)[0])

In [24]:
joblib.dump(model_rf, "../models/fill_forecast_rf.pkl")
print("Forecast model saved.")

Forecast model saved.